[package]
name = "parsing-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
parsing = { path = "../parsing" }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"
